name: shopping_list
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  connectivity_plus: ^4.0.0
  firebase_database: ^10.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  google_fonts: ^4.0.4
  http: ^0.13.6
  riverpod: ^2.3.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
